// packages/client/src/components/jlpt/read/JLPT-ReadVocabCard.tsx
import StarIcon from '@/components/icon/StarIcon'
import type { JLPT_ReadVocab } from '@root/models'
import { NCard, NButton } from 'naive-ui'

interface Props {
    vocab: JLPT_ReadVocab
    class?: string
}
export default function JLPT_ReadVocabCard(props: Props) {
    return (
        <NCard
            hoverable
            title={props.vocab.word}
            size="small"
            headerExtra={() => (
                <NButton
                    quaternary
                    circle
                    size="small"
                    type="warning"
                    renderIcon={() => <StarIcon size={22} />}
                />
            )}
        >
            {props.vocab.definition}
        </NCard>
    )
}

// packages/client/src/components/jlpt/read/JLPT-ReadVocabCard.vue
<template>
    <n-card hoverable :title="vocab.word" size="small">
        <template #header-extra>
            <n-button quaternary circle size="small" type="warning">
                <template #icon>
                    <StarIcon size="20" />
                </template>
            </n-button>
        </template>
        {{ vocab.definition }}
    </n-card>
</template>

<script setup lang="ts">
import StarIcon from '@/components/icon/StarIcon.vue'
import type { JLPT_ReadVocab } from '@root/models'
import { NCard, NButton } from 'naive-ui'

defineProps<{
    vocab: JLPT_ReadVocab
}>()
</script>
